<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pil_tunjangan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tampilan_model');
        $this->load->model('Pil_tunjangan_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->Tampilan_model->admin();
    }

    public function index()
    {
        $this->Tampilan_model->layar('pil_tunjangan/pil_tunjangan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pil_tunjangan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pil_tunjangan_model->get_by_id($id);
        if ($row) {
            $data = array(
    		'id' => $row->id,
    		'nama_tunjangan' => $row->nama_tunjangan,
	    );
            $this->Tampilan_model->layar('pil_tunjangan/pil_tunjangan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/pil_tunjangan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('admin/pil_tunjangan/create_action'),
    	    'id' => set_value('id'),
    	    'nama_tunjangan' => set_value('nama_tunjangan'),
	);
        $this->Tampilan_model->layar('pil_tunjangan/pil_tunjangan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		    'nama_tunjangan' => $this->input->post('nama_tunjangan',TRUE),
	    );

            $this->Pil_tunjangan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/pil_tunjangan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pil_tunjangan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('admin/pil_tunjangan/update_action'),
        		'id' => set_value('id', $row->id),
        		'nama_tunjangan' => set_value('nama_tunjangan', $row->nama_tunjangan),
	    );
            $this->Tampilan_model->layar('pil_tunjangan/pil_tunjangan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/pil_tunjangan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		    'nama_tunjangan' => $this->input->post('nama_tunjangan',TRUE),
	    );

            $this->Pil_tunjangan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/pil_tunjangan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pil_tunjangan_model->get_by_id($id);

        if ($row) {
            $this->Pil_tunjangan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/pil_tunjangan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/pil_tunjangan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_tunjangan', 'nama tunjangan', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pil_tunjangan.php */
/* Location: ./application/controllers/Pil_tunjangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-05 06:19:37 */
/* http://harviacode.com */