<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pil_jabatan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pil_jabatan_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->load->model('Tampilan_model');
    }

    public function index()
    {
        $this->Tampilan_model->layar('pil_jabatan/pil_jabatan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pil_jabatan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pil_jabatan_model->get_by_id($id);
        if ($row) {
            $data = array(
		      'id' => $row->id,
		      'jabatan' => $row->jabatan,
	    );
            $this->Tampilan_model->layar('pil_jabatan/pil_jabatan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/pil_jabatan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('admin/pil_jabatan/create_action'),
	       'id' => set_value('id'),
	       'jabatan' => set_value('jabatan'),
	);
        $this->Tampilan_model->layar('pil_jabatan/pil_jabatan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		  'jabatan' => $this->input->post('jabatan',TRUE),
	    );

            $this->Pil_jabatan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/pil_jabatan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pil_jabatan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('admin/pil_jabatan/update_action'),
		'id' => set_value('id', $row->id),
		'jabatan' => set_value('jabatan', $row->jabatan),
	    );
            $this->Tampilan_model->layar('pil_jabatan/pil_jabatan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/pil_jabatan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'jabatan' => $this->input->post('jabatan',TRUE),
	    );

            $this->Pil_jabatan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/pil_jabatan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pil_jabatan_model->get_by_id($id);

        if ($row) {
            $this->Pil_jabatan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/pil_jabatan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/pil_jabatan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('jabatan', 'jabatan', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pil_jabatan.php */
/* Location: ./application/controllers/Pil_jabatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-10 06:25:26 */
/* http://harviacode.com */