<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Absen_model extends CI_Model
{

    public $table = 'jam_kerja';
    public $id = 'id';
    public $id_users = 'id_users';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id_users = '', $bulan = '', $tahun = '')
    {

        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();

        $this->datatables->select('j.id, j.tgl, j.jam_masuk, j.jam_pulang, j.lembur, j.tidak_masuk, j.keterangan,j.status,j.lokasi_masuk,j.lokasi_pulang,j.foto_masuk,j.foto_pulang, (CASE WHEN j.status = "1" THEN "MASUK" WHEN j.status = "2" THEN "PULANG" ELSE "" END) AS nm_status, p.nama_pegawai');
        $this->datatables->from('jam_kerja AS j');
        //add this line for join
        $this->datatables->join('pegawai AS p', 'j.id_users = p.id_users');
        $this->datatables->join('users AS u', 'u.id = p.id_users');
        $this->datatables->where('u.id!=', $id_users);
        $this->datatables->where('u.id_kantor', $kantor_id->id_kantor);
        // where
        if ($id_users != 'semua') {
            $this->datatables->where('j.id_users', $id_users);
        }
        if ($bulan != 'semua') {
            $this->datatables->where('SUBSTRING(j.tgl,4,2) = "' . sprintf('%02d', $bulan) . '"');
        }
        if ($tahun != 'semua') {
            $this->datatables->where('SUBSTRING(j.tgl,7,4) = "' . $tahun . '"');
        }
        // column
        $this->datatables->add_column('action', anchor(site_url('admin/absen/update/$1'), '<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>') . "&nbsp;&nbsp;" . anchor(site_url('admin/absen/delete/$1'), '<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->select('*');
        $this->db->from('jam_kerja as jk');
        $this->db->join('pegawai as p', 'p.id = jk.id_users', 'left');
        $this->db->order_by('p.id', 'ASC');
        return $this->db->get()->result();
    }

    function get_today()
    {
        $this->db->select('*');
        $this->db->from('jam_kerja as jk');
        $this->db->join('users as u', 'u.id = jk.id_users');
        $this->db->where('tgl', date('d-m-Y'));
        $this->db->join('pegawai as p', 'p.id_users = u.id');
        return $this->db->get()->result();
    }

    function get_by_month($bulan_tahun)
    {
        $this->db->select('*');
        $this->db->from('jam_kerja as jk');
        $this->db->join('pegawai as p', 'p.id = jk.id_users', 'left');
        $this->db->where('RIGHT(jk.tgl,7) = ' . '"' . $bulan_tahun . '"');
        $this->db->order_by('jk.' . $this->id, $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id users
    function get_by_id_users($id_users)
    {
        $this->db->where($this->id_users, $id_users);
        return $this->db->get($this->table)->row();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete
    function delete($id)
    {
        $this->db->where('id', $id);
        $this->db->delete($this->table);
    }
}

/* End of file Hari_kerja_model.php */
/* Location: ./application/models/Hari_kerja_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-30 05:50:21 */
/* http://harviacode.com */
