<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');
class Hari_kerja_model extends CI_Model
{

    public $table = 'hari_kerja';

    public $id = 'id';

    public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
    }
    // datatables
    function json($tahun = '', $bulan = '')
    {

        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();

        $this->datatables->select('h.id, h.tahun, h.jam_kerja, b.bulan AS nm_bulan');
        $this->datatables->from('hari_kerja AS h');
        //add this line for join
        $this->datatables->join('bulan AS b', 'h.bulan = b.id');
        $this->datatables->where('h.id_kantor', $kantor_id->id_kantor);
        // where
        if (!empty($tahun)) {
            $this->datatables->where('h.tahun', $tahun);
        }
        if (!empty($bulan)) {
            $this->datatables->where('h.bulan', $bulan);
        }
        // column
        $this->datatables->add_column('action', anchor(site_url('admin/hari_kerja/read/$1'), '<button class="btn btn-xs btn-success"><i class="ace-icon fa fa-check bigger-120"></i></button>') . "&nbsp;&nbsp;" . anchor(site_url('admin/hari_kerja/update/$1'), '<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>') . "&nbsp;&nbsp;" . anchor(site_url('admin/hari_kerja/delete/$1'), '<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->select('hk.*,b.bulan as bulan_huruf', $id);
        $this->db->from('hari_kerja hk');
        $this->db->join('bulan b', 'b.id=hk.bulan');
        // $this->db->where('', $id);
        // $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('bulan', $q);
        $this->db->or_like('hari_kerja', $q);
        // $this->db->or_like('jam_masuk', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('bulan', $q);
        $this->db->or_like('jam_kerja', $q);
        // $this->db->or_like('hari_masuk', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_by_bulan_tahun($bulan, $tahun)
    {
        $this->db->where('bulan', $bulan);
        $this->db->where('tahun', $tahun);
        $row = $this->db->get('hari_kerja')->row();
        return $row->jam_kerja;
    }
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}
/* End of file Hari_kerja_model.php */
/* Location: ./application/models/Hari_kerja_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-30 05:50:21 */
/* http://harviacode.com */