<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Info_model extends CI_Model
{

    public $table = 'info';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {


        
        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();
        $this->datatables->select('info.id,info.tgl,info.info,pil_level.level as tujuan');
        $this->datatables->from('info');
        //add this line for join
        $this->datatables->join('pil_level', 'info.tujuan = pil_level.id','left');
        $this->datatables->where('info.id_kantor',$kantor_id->id_kantor);
        $this->datatables->add_column('action', anchor(site_url('admin/info/read/$1'),'<button class="btn btn-xs btn-success"><i class="ace-icon fa fa-check bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/info/update/$1'),'<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/info/delete/$1'),'<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();
        $this->db->order_by($this->id, $this->order);
        return $this->db->where('id_kantor', $kantor_id->id_kantor)->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_info($users_level){



        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();

        $this->db->order_by('tgl','desc');
        $this->db->where('id_kantor',$kantor_id->id_kantor);
        $this->db->group_by('tgl');
        $result = $this->db->get('info')->result();
        $data_info = array();
        foreach ($result as $info) {
            $d_info = $this->get_by_date($info->tgl,$users_level);
            if(!empty($d_info)){
            $data_info[] = array(
                              'tgl'=>$info->tgl,
                              'info'=>$d_info
                            );
            }
        }
        return $data_info;
    }
    function get_by_date($tgl,$users_level){
        $this->db->where('tgl', $tgl);
        $this->db->order_by('id', 'desc');
        $result = $this->db->get('info')->result();
        $data = array();
        foreach ($result as $r) {
            if($r->tujuan == $users_level || $r->tujuan == 0){
                $data[] = $r->info;
            }
        }
        return $data;
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('info', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('tgl', $q);
    	$this->db->or_like('info', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Info_model.php */
/* Location: ./application/models/Info_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-04 05:00:28 */
/* http://harviacode.com */