<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jadwal_monitor_model extends CI_Model
{

    public $table = 'jadwal_monitor';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {

        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();

        $this->db->select('jm.*');
        $this->db->from('jadwal_monitor AS jm');
        $this->db->where('jm.id_kantor', $kantor_id->id_kantor);
        $this->db->order_by('jm.id','DESC');
        return $this->db->get()->result();
        // return $all;
    }

    // get data by jam
    function get_by_jam_aktif($jam)
    {
        $this->db->where('status', 1);
        $this->db->where('jam', $jam);
        return $this->db->get($this->table)->row();
    }

    // get data by indeks
    function get_by_indeks($indeks)
    {
        $this->db->where('indeks', $indeks);
        return $this->db->get($this->table)->row();
    }
    function get_by_id_kantor($id)
    {
        $this->db->where('id_kantor', $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
    
        $data['created_date'] = date('Y-m-d H:i:s');
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $data['updated_date'] = date('Y-m-d H:i:s');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Jadwal_monitor_model.php */
/* Location: ./application/models/Jadwal_monitor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-03 07:49:45 */
/* http://harviacode.com */
