<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');

class Kantor_lokasi_model extends CI_Model
{

    public $table = 'kantor_lokasi';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {

    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id_kantor($id_kantor)
    {
        $this->db->select('k.*');
        $this->db->from('kantor_lokasi as k');
        $this->db->where('k.id_kantor',$id_kantor);
        // $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }

    // insert data
    function insert($data)
    {
        $data['created_date'] = date('Y-m-d H:i:s');
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Kantor_model.php */
/* Location: ./application/models/Kantor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-23 03:57:51 */
/* http://harviacode.com */
