<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pil_tingkat_model extends CI_Model
{

    public $table = 'pil_tingkat';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $user_id = $this->session->userdata('user_id');
        $kantor_id = $this->db->select('id_kantor')
                ->from('users')
                ->where('id',$user_id)
                ->get()
                ->row();
        $this->datatables->select('pt.id as id,pt.tingkat,pt.ket,pj.jabatan');
        $this->datatables->from('pil_tingkat as pt');
        //add this line for join
        $this->datatables->join('pil_jabatan as pj', 'pj.id = pt.id_jabatan','left');
        $this->datatables->where('pj.id_kantor', $kantor_id->id_kantor);
        $this->datatables->add_column('action', anchor(site_url('admin/pil_tingkat/read/$1'),'<button class="btn btn-xs btn-success"><i class="ace-icon fa fa-check bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/pil_tingkat/update/$1'),'<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/pil_tingkat/delete/$1'),'<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
       
                
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_jabatan($id)
    {
        $this->db->where('id_jabatan', $id);
        return $this->db->get('pil_tingkat')->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tingkat', $q);
	$this->db->or_like('ket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('tingkat', $q);
    	$this->db->or_like('ket', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_by_id_jabatan($id)
    {
        $this->db->where('id_jabatan', $id);
        return $this->db->get('pil_tingkat')->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pil_tingkat_model.php */
/* Location: ./application/models/Pil_tingkat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-02 01:51:29 */
/* http://harviacode.com */