<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pil_transaksi_model extends CI_Model
{

    public $table = 'pil_transaksi';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('pt.id, pt.nm_transaksi, pt.id_akun_debet, pt.id_akun_kredit, ak_debet.akun AS akun_debet, ak_kredit.akun AS akun_kredit');
        $this->datatables->from('pil_transaksi AS pt');
        //add this line for join
        $this->datatables->join('akun AS ak_debet', ' pt.id_akun_debet = ak_debet.id');
        $this->datatables->join('akun AS ak_kredit', ' pt.id_akun_kredit = ak_kredit.id');

        $this->datatables->add_column('action', anchor(site_url('admin/pil_transaksi/read/$1'),'<button class="btn btn-xs btn-success"><i class="ace-icon fa fa-check bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/pil_transaksi/update/$1'),'<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/pil_transaksi/delete/$1'),'<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nm_transaksi', $q);
	$this->db->or_like('id_akun_debet', $q);
	$this->db->or_like('id_akun_kredit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nm_transaksi', $q);
	$this->db->or_like('id_akun_debet', $q);
	$this->db->or_like('id_akun_kredit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pil_transaksi_model.php */
/* Location: ./application/models/Pil_transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-04 02:18:07 */
/* http://harviacode.com */