<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Registrasi_kantor_model extends CI_Model
{

    public $table = 'registrasi_kantor';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('rk.id, rk.perusahaan, rk.alamat, rk.no_telp_perusahaan, rk.bidang_bisnis, rk.jml_karyawan, rk.nama_pemohon, rk.no_telp_pemohon, rk.jabatan_pemohon, rk.email, rk.created_date, rk.status, IF(k.id IS NULL, 0, 1) AS is_kantor_created');
        $this->datatables->from('registrasi_kantor rk');
        $this->datatables->join('kantor k', 'rk.perusahaan = k.nama_kantor', 'left');
        $this->datatables->add_column('action', anchor(site_url('registrasi_kantor/update/$1'), 'Update') . " | " . anchor(site_url('registrasi_kantor/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $data['created_date'] = date('Y-m-d H:i:s');
        $data['status'] = 1;
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Registrasi_kantor_model.php */
/* Location: ./application/models/Registrasi_kantor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-11-27 08:57:13 */
/* http://harviacode.com */
