<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');
class Tasks_model extends CI_Model
{

    public $table = 'tasks';

    public $id = 'id';

    public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
    }
    // datatables
    function json($id)
    {
        $this->datatables->select('t.id,t.id_project,t.date_created,t.task,t.description,t.id_status');
        $this->datatables->from('tasks as t');
        //add this line for join
        $this->datatables->join('project as p', 'p.id = t.id_project');
        $this->datatables->where('p.id_kantor',$id);
        $this->datatables->add_column('action', anchor(site_url('admin/tasks/read/$1'), '<button class="btn btn-sm btn-primary"> <i class="ace-icon fa fa-check bigger-120"></i></button>') . "  " . anchor(site_url('admin/tasks/update/$1'), '<button class="btn btn-sm btn-success"><i class="ace-icon fa fa-pencil bigger-120"></i></button>') . "  " . anchor(site_url('admin/tasks/delete/$1'), '<button class="btn btn-sm btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->select('t.*,p.project');
        $this->db->from('tasks t');
        $this->db->join('project p' , 'p.id=t.id_project');
        $this->db->where('t.id', $id);
        return $this->db->get()->row();
        
        // $this->db->where($this->id, $id);
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_project', $q);
        $this->db->or_like('date_created', $q);
        $this->db->or_like('task', $q);
        $this->db->or_like('description', $q);
        $this->db->or_like('id_status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_project', $q);
        $this->db->or_like('date_created', $q);
        $this->db->or_like('task', $q);
        $this->db->or_like('description', $q);
        $this->db->or_like('id_status', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}
/* End of file Tasks_model.php */
/* Location: ./application/models/Tasks_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-05 10:42:24 */
/* http://harviacode.com */
