<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tidak_masuk_model extends CI_Model
{

    public $table = 'tidak_masuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id_users = '', $bulan = '', $tahun = '') {
        
        $this->datatables->select('t.id, t.tgl, t.id_users, t.tidak_masuk,t.keterangan, p.nama_pegawai, ptm.ket_tidak_masuk');
        $this->datatables->from('tidak_masuk AS t');
        //add this line for join
        $this->datatables->join('pegawai AS p', 't.id_users = p.id_users');
        $this->datatables->join('pil_tidak_masuk AS ptm', 't.tidak_masuk = ptm.id');
        // where
        if ($id_users!='semua') {
            $this->datatables->where('t.id_users', $id_users);
        }
        if ($bulan!='semua') {
            $this->datatables->where('SUBSTRING(t.tgl,6,2) = "'.sprintf('%02d', $bulan).'"');
        }
        if ($tahun!='semua') {
            $this->datatables->where('SUBSTRING(t.tgl,1,4) = "'.$tahun.'"');
        }
        // column
        
        $this->datatables->add_column('action', anchor(site_url('admin/tidak_masuk/read/$1'),'<button class="btn btn-xs btn-success"> <i class="ace-icon fa fa-check bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/tidak_masuk/update/$1'),'<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>')."&nbsp;&nbsp;".anchor(site_url('admin/tidak_masuk/delete/$1'),'<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('t.*,p.nama_pegawai,ptm.ket_tidak_masuk');
        $this->db->from('tidak_masuk as t');
        $this->db->join('pegawai as p', 'p.id_users=t.id_users');
        $this->db->join('pil_tidak_masuk ptm', 'ptm.id=t.tidak_masuk');
        $this->db->where('t.id', $id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('tidak_masuk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('tidak_masuk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tidak_masuk_model.php */
/* Location: ./application/models/Tidak_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-03 04:12:12 */
/* http://harviacode.com */