<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');

class Kantor extends CI_Controller
{

    public $active = array('active_utilities' => 'active_kantor');

    function __construct()
    {
        parent::__construct();
        $this->load->library('form_validation');
        $this->load->library('datatables');
        $this->load->model('Tampilan_model');
        $this->load->model('Kantor_model');
        $this->load->model('Kantor_lokasi_model');
        $this->Tampilan_model->admin();
    }

    public function index()
    {
        $data = [];
        $this->Tampilan_model->layar('kantor/kantor_list', $data, $this->active);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Kantor_model->json();
    }

    public function read($id)
    {
        $row = $this->Kantor_model->get_by_id($id);
        if ($row) {
            $data = [
                'id' => $row->id,
                'kantor' => $row->kantor,
                'lat' => set_value('kantor', $row->lat),
                'long' => set_value('kantor', $row->long),
            ];
            $this->load->view('kantor/kantor_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kantor'));
        }
    }

    public function create()
    {
        $data = [
            'button' => 'Create',
            'action' => site_url('admin/kantor/create_action'),
            'id' => set_value('id'),
            'kantor' => set_value('kantor'),
        ];
        $this->Tampilan_model->layar('kantor/kantor_form', $data, $this->active);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = [
                'kantor' => $this->input->post('kantor', TRUE),
            ];
            $this->Kantor_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/kantor'));
        }
    }

    public function update($id)
    {
        $row = $this->Kantor_model->get_by_id($id);
        if ($row) {
            $data = [
                'button' => 'Update',
                'action' => site_url('admin/kantor/update_action'),
                'id' => set_value('id', $row->id),
                'nama_kantor' => set_value('kantor', $row->nama_kantor),
                'lat' => set_value('kantor', $row->lat),
                'long' => set_value('kantor', $row->long),
            ];
            $this->Tampilan_model->layar('kantor/kantor_form', $data, $this->active);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kantor'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $id = $this->input->post('id', TRUE);
            $data = [
                'nama_kantor' => $this->input->post('kantor', TRUE),
               
            ];
            $data_lat_long =[
                'lat' => $this->input->post('lat', TRUE),
                'long' => $this->input->post('long', TRUE),
            ];

            $kantor = $this->Kantor_lokasi_model->get_by_id_kantor($id);
            // var_dump($kantor);

            $this->Kantor_model->update($id, $data);
            $this->Kantor_lokasi_model->update($kantor->id_kantor, $data_lat_long);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/kantor'));
            // var_dump($data);
        }
    }

    public function delete($id)
    {
        $row = $this->Kantor_model->get_by_id($id);
        if ($row) {
            $this->Kantor_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/kantor'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kantor'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('kantor', 'nama kantor', 'trim|required');
        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Kantor.php */
/* Location: ./application/controllers/Kantor.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-10-23 03:57:51 */
/* http://harviacode.com */
