<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kritik_saran extends CI_Controller
{
    public $active = array('active_utilities' => 'active_kisar');
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kritik_saran_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->load->model('Tampilan_model');
        $this->Tampilan_model->admin();
    }

    public function index()
    {
        $this->Tampilan_model->layar('kritik_saran/kritik_saran_list', null, $this->active);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Kritik_saran_model->json();
    }

    public function read($id) 
    {
        $row = $this->Kritik_saran_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'tgl' => $row->tgl,
		'isi' => $row->isi,
	    );
            $this->Tampilan_model->layar('kritik_saran/kritik_saran_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kritik_saran'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kritik_saran/create_action'),
	    'id' => set_value('id'),
	    'tgl' => set_value('tgl'),
	    'isi' => set_value('isi'),
	);
        $this->Tampilan_model->layar('kritik_saran/kritik_saran_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'tgl' => $this->input->post('tgl',TRUE),
		'isi' => $this->input->post('isi',TRUE),
	    );

            $this->Kritik_saran_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kritik_saran'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kritik_saran_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kritik_saran/update_action'),
		'id' => set_value('id', $row->id),
		'tgl' => set_value('tgl', $row->tgl),
		'isi' => set_value('isi', $row->isi),
	    );
            $this->Tampilan_model->layar('kritik_saran/kritik_saran_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kritik_saran'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'tgl' => $this->input->post('tgl',TRUE),
		'isi' => $this->input->post('isi',TRUE),
	    );

            $this->Kritik_saran_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kritik_saran'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kritik_saran_model->get_by_id($id);

        if ($row) {
            $this->Kritik_saran_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kritik_saran'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kritik_saran'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('tgl', 'tgl', 'trim|required');
	$this->form_validation->set_rules('isi', 'isi', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kritik_saran.php */
/* Location: ./application/controllers/Kritik_saran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-04 10:57:32 */
/* http://harviacode.com */